# fly.toml app configuration file generated for witcher-quiz-bot on 2025-08-26T13:20:49+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'witcher-quiz-bot'
primary_region = 'waw'

[build]

[processes]
  app = "python witcher_quiz_bot.py"

[experimental]
  auto_stop_machines = false
  auto_start_machines = true

[deploy]
  strategy = "immediate"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
